<!--
`accessors:true` hast to be set per component because of the svelte-language-server bug, otherwise accessors would be falsely detected as missing and highlighted as errors.
svelthree uses svelte-accmod, where accessors are always `true`, regardless of `svelte:options`.  
-->
<svelte:options accessors />

<!--
@component
**svelthree** _Scene_ Component.
[ tbd ]  Link to Docs.
-->
<script lang="ts">
	import { beforeUpdate, onMount, afterUpdate, onDestroy, getContext, setContext, tick } from "svelte"
	import { get_current_component } from "svelte/internal"
	import { self as _self } from "svelte/internal"
	import { c_rs, c_lc, c_mau, c_dev, verbose_mode, get_comp_name } from "../utils/SvelthreeLogger"
	import type { LogLC, LogDEV } from "../utils/SvelthreeLogger"
	import type { SvelthreeShadowDOMElement } from "../types/types-extra"
	import { if$_instance_change } from "../logic/if$"
	import { remove_instance, recreate_shadow_dom_el, set_initial_userdata, find_in_canvas } from "../logic/shared"

	import type { Euler, Matrix4, Quaternion, Vector3 } from "three"
	import type { Object3D } from "three"
	import type { Targetable } from "../types/types-extra"

	import { svelthreeStores } from "svelthree/stores"
	import { PropUtils, SvelthreeProps } from "../utils"

	import { SvelthreeAni } from "../ani"
	import type { SvelthreeAnimationFunction, SvelthreeAnimation } from "../types/types-extra"

	import SvelthreeInteraction from "../components-internal/SvelthreeInteraction.svelte"
	import type { RaycastArray } from "../utils/RaycastArray"

	import { createEventDispatcher } from "svelte"
	import type { InteractionEventDispatcher } from "../types/types-extra"

	import type { Writable } from "svelte/store"
	import type { SvelthreeModifiersProp } from "../types/types-extra"
	import type {
		SvelthreePointerEventHandler,
		SvelthreeFocusEventHandler,
		SvelthreeKeyboardEventHandler,
		SvelthreeWheelEventHandler
	} from "../types/types-extra"

	import { BoxHelper } from "three"
	import { get_root_scene } from "../utils/SceneUtils"

	import { Scene as THREE_Scene } from "three"
	import type { PropsScene } from "../types/types-comp-props"
	import type { FogBase, Color, Mapping, Texture } from "three"
	import { EquirectangularReflectionMapping, TextureLoader } from "three"
	import type { RemoveFirst } from "../types/types-extra"
	import type { PropButton, PropLink } from "../types/types-comp-props"

	/**
	 *  SVELTEKIT  SSR /
	 * `browser` is needed for the SvelteKit setup (SSR / CSR / SPA).
	 * For non-SSR output in RollUp only and Vite only setups (CSR / SPA) we're just mimicing `$app/environment` where `browser = true`,
	 * -> TS fix: `$app/environment` mapped to `src/$app/environment` via svelthree's `tsconfig.json`'s `path` property.
	 * -> RollUp only setup: replace `$app/environment` with `../$app/environment`
	 * The import below will work out-of-the-box in a SvelteKit setup.
	 */
	import { browser } from "$app/environment"

	const self = get_current_component()
	const c_name = get_comp_name(self)
	/** svelthree component's type (e.g. component `Foo` is of type 'Foo' etc.) */
	export const type: string = c_name

	const shadow_root: Writable<{ element: HTMLDivElement }> = getContext("shadow_root")
	let shadow_root_el: HTMLDivElement
	$: shadow_root_el = $shadow_root.element

	const verbose: boolean = verbose_mode()

	export let log_all = false
	export let log_dev: { [P in keyof LogDEV]: LogDEV[P] } = log_all ? { all: true } : undefined
	export let log_rs: boolean = log_all
	export let log_lc: { [P in keyof LogLC]: LogLC[P] } = log_all ? { all: true } : undefined
	export let log_mau: boolean = log_all

	const dispatch_interaction = createEventDispatcher<InteractionEventDispatcher>()

	/** `id` is used to identify / assign a Scene to a 'WebGLRenderer' component.
	 * `id` is **not needed if** a Scene component is a child of any Object3D (e.g. another Scene) in this case
	 * it will be treated as a standard Object3D asset. */
	export let id: string = undefined

	const sti: number = getContext("store_index")

	const svelthreeStore = $svelthreeStores[sti]

	/** [ **feature**: allow providing (_injection_) of (_already created_) threejs object instances ].
	 * `create` is an internal indicator for how the component's corresponding threejs object instance has to be / has been created.
	 * It's being set to `false` on initialization if an (_already created_) threejs object instance was provided,
	 * otherwise it's set to `true`, means a new threejs object instance will be created. */
	let create = false

	/** The (three) instance that was shared to this component as it's 'parent' which can be either another instance / object or a scene / root scene. */
	let our_parent: Object3D = undefined

	/** Shadow DOM element generated by our parent component (_not `Canvas`_) shared with this component (child) via context.
	Fallback is `scene_shadow_dom_el` or `shadow_root_el` in case of the `Scene` component. */
	let our_parent_shadow_dom_el: SvelthreeShadowDOMElement = undefined

	/** Shadow DOM element generated by this component. Shared by this component (as parent) to it's children via context as "parent_shadow_dom_el". */
	let shadow_dom_el: SvelthreeShadowDOMElement = undefined
	export const get_shadow_dom_el = (): SvelthreeShadowDOMElement => shadow_dom_el

	/** Specify the component / three.js object instance to act as an HTML `<button>` element. */
	export let button: PropButton = undefined

	/** Specify the component / three.js object instance to act as an HTML `<a>` element. */
	export let link: PropLink = undefined

	/** Returns the `scene` instance created by the component & allows providing (_injection_) of (_already created / premade_) `THREE.Scene` instances. */
	export let scene: THREE_Scene = undefined
	let scene_uuid: string = undefined

	/** Sets the `name` property of the created / injected three.js instance. */
	export let name: string = undefined
	let scene_is_active: boolean = undefined

	export const is_svelthree_component = true
	export const is_svelthree_scene = true

	//  ONCE  ON  INITIALIZATION  //

	if (scene) {
		create = false
		on_instance_provided()
	} else {
		create = true
	}

	//  INJECTION  ONCE  ON  INITIALIZATION  //

	/** Executed when / if an instance was provided **on initializiation** -> only once if at all! */
	function on_instance_provided(): void {
		if (scene.type === "Scene") {
			//nothing
		} else {
			throw new Error(
				`SVELTHREE > ${c_name} provided 'scene' instance has wrong type '${scene.type}', should be '${c_name}'!`
			)
		}
	}

	//  INJECTION  ONCE  ON  INITIALIZATION  //

	if (!create) {
		// get the instance that was shared to us as our 'parent' or use fallback.
		// IMPORTANT  is allowed to be `undefined` in the `Scene` component!
		our_parent = getContext("parent") || getContext("scene")
		// get the shadow DOM element that was shared to us by our parent component or use fallback.
		// IMPORTANT  is allowed to be `undefined` in the `Scene` component!
		our_parent_shadow_dom_el = getContext("parent_shadow_dom_el")

		// share created object (three) instance to all children (slots) as 'parent'.
		setContext("parent", scene)

		// SVELTEKIT  SSR /
		if (browser) create_shadow_dom()
	}

	$: if (!scene && create) {
		// handle Scene as normal Object3D if it has a parent

		scene = new THREE_Scene()

		set_initial_userdata(scene, self)

		// get the instance that was shared to us as our 'parent' or use fallback.
		// IMPORTANT  is allowed to be `undefined` in the `Scene` component!
		our_parent = getContext("parent") || getContext("scene")
		// get the shadow DOM element that was shared to us by our parent component or use fallback.
		// IMPORTANT  is allowed to be `undefined` in the `Scene` component!
		our_parent_shadow_dom_el = getContext("parent_shadow_dom_el")

		// share created object (three) instance to all children (slots) as 'parent'.
		setContext("parent", scene)

		// SVELTEKIT  SSR /
		if (browser) create_shadow_dom()

		if (!our_parent) {
			// 'scene' is a 'root' Scene, direct child of the Canvas component

			// 'scene' is a 'root' Scene, it should have an 'id'.
			if (!id) {
				console.warn(
					"SVELTHREE > Scene : an 'id' prop (not empty String) for Scenes in order to assign them to a 'WebGLRenderer' component!",
					{ id: id }
				)
				throw new Error("SVELTHREE Exception (see warning above)")
			}

			scene.userData.id = id
			scene.userData.sti = sti
			// TODO / TOFIX  // HÄÄÄ??? This is unused / not implemented!!!
			//scene.userData.animations = []

			scene_is_active = false
			scene.userData.isActive = scene_is_active

			svelthreeStore.scenes.push({ scene: scene, id: id, isActive: false })
		}

		// every scene spreads it's onw instance to children overwriting the 'root scene' instance
		// so if we need a reference to the topmost 'root scene' from an object inside some nested
		// scene, we have to search for it, see e.g. the `CubeCamera` component
		setContext("scene", scene)

		if (verbose && log_dev) console.debug(...c_dev(c_name, `${scene.type} created!`, { scene }))
	}

	// ---  AFTER  INITIALIZATION  --- //

	// set scene_uuid the first time
	$: if (scene && scene_uuid === undefined) set_uuid()

	function set_uuid(): void {
		scene_uuid = scene.uuid
	}

	// GENERATOR REMARK: 'reactive_re_creation_logic' not implemented for 'Scene'!

	// GENERATOR REMARK: 'parent_logic_if_inst_not_provided' excluded for 'Scene'!

	function create_shadow_dom(): void {
		// create / recreate and share our own shadow_dom_el as parent_shadow_dom_el
		shadow_dom_el = recreate_shadow_dom_el(shadow_dom_el, our_parent_shadow_dom_el, button, link, c_name)

		if (shadow_dom_el) {
			setContext("parent_shadow_dom_el", shadow_dom_el)
		} else {
			if (!shadow_dom_el) console.error(`SVELTHREE > ${c_name} : 'shadow_dom_el' was not created!`, shadow_dom_el)
		}
	}

	// IMPORTANT  append scenes only when `shadow_root_el` is available!
	$: if (shadow_root_el && shadow_dom_el) {
		let target_shadow_dom = our_parent_shadow_dom_el || shadow_root_el

		if (!shadow_dom_el.parentNode) {
			if (target_shadow_dom) {
				target_shadow_dom.appendChild(shadow_dom_el)
			} else {
				console.error(
					`SVELTHREE > ${c_name} > couldn't append shadow dom, no 'target_shadow_dom'!`,
					target_shadow_dom
				)
			}
		}
	}

	// accessability -> shadow dom focusable
	export let tabindex: number = undefined

	$: if (shadow_dom_el && tabindex !== undefined) {
		shadow_dom_el.tabIndex = tabindex
	}

	// accessability -> shadow dom wai-aria
	// eslint-disable-next-line no-undef
	export let aria: Partial<ARIAMixin> = undefined

	$: if (shadow_dom_el && aria !== undefined) {
		for (const key in aria) {
			if (key === "ariaLabel") {
				// add specified `ariaLabel` as text to shadow DOM `<div>` element ONLY (for better reader support / indexing (?))
				if (!link && !button) {
					//  TODO  RECONSIDER  needs to be tested more, may be obsolete (?).
					shadow_dom_el.innerText += `${aria[key]}`
				}
			}

			shadow_dom_el[key] = aria[key]
		}
	}

	// this reactive statement willl be triggered on any 'scene' instance change (also e.g. `scene.foo = value`)
	$: if (scene) if$_instance_change(scene, our_parent, scene_uuid, create, "scene", name, handle_instance_change)

	/** Called from by the `if$_instance_change` logic if needed. */
	function handle_instance_change(): void {
		let old_raycast = false
		let old_block = false

		if ((scene_uuid && scene.uuid !== scene_uuid) || !scene_uuid) {
			const uuid_to_remove: string = scene_uuid || scene.uuid
			const old_instance: Object3D = find_in_canvas($svelthreeStores[sti].scenes, uuid_to_remove)

			remove_instance(old_instance, "scene", scene, self)

			// remove `old_instance` from raycast if needed
			if (raycast.includes(old_instance)) {
				old_raycast = true
				old_block = old_instance.userData.block
				raycast.splice(old_instance.userData.index_in_raycast, 1)
			}

			if (props) sProps = new SvelthreeProps(scene)
		}

		set_initial_userdata(scene, self)

		// add 'scene' (provided instance) to raycast if needed
		if (old_raycast) {
			if (!raycast.includes(scene)) {
				scene.userData.block = old_block // will this somehow be handeled automatically?
				raycast.push(scene)
			}
		}

		our_parent.add(scene)
		scene_uuid = scene.uuid
		scene_obj.value = scene

		if (verbose && log_dev) {
			console.debug(
				...c_dev(c_name, `${scene.type} was added to ${our_parent.type}!`, {
					scene,
					total: scene.children.length
				})
			)
		}
	}

	/** Set `Scene`'s `.matrixAutoUpdate` which will also be set for all objects (*components*) in the scene (*default is `true`*).
	 * You can override `Scene`'s `.matrixAutoUpdate` per component by setting their own `mau` shorthand attribute to `true` or `false`.
	 * Also: `mau` can be changed on-the-fly. */
	export let mau: boolean = undefined

	// IMPORTANT  +  COOL!  SVELTE  this runs only on 'mau' change!
	$: if (mau !== undefined) {
		mau === true ? enableSceneAuto() : disableSceneAuto()
	}

	function enableSceneAuto() {
		if (verbose && log_rs) console.debug(...c_rs(c_name, "mau > enableSceneAuto!", { mau }))

		// IMPORTANT  lets the renderer perform scene.updateMatrixWorld() on every render pass.
		scene.autoUpdate = true

		// IMPORTANT  `scene.updateMatrixWorld()` will always call `matrixUpdate()` first which will set `scene.matrixWorldNeedsUpdate` to `true`.
		scene.matrixAutoUpdate = true

		if (verbose && log_mau) console.debug(...c_mau(c_name, "enableSceneAuto! scene.autoUpdate:", scene.autoUpdate))
		if (verbose && log_mau)
			console.debug(...c_mau(c_name, "enableSceneAuto! scene.matrixAutoUpdate:", scene.matrixAutoUpdate))
	}

	function disableSceneAuto() {
		if (verbose && log_rs) console.debug(...c_rs(c_name, "mau > disableSceneAuto!", { mau }))

		// IMPORTANT  lets the renderer perform scene.updateMatrixWorld() on every render pass -> we don't have to do it in the component!.
		scene.autoUpdate = true

		// IMPORTANT  prevents calling `matrixUpdate()` on `scene.updateMatrixWorld()`
		// -> won't set `scene.matrixWorldNeedsUpdate = true`...
		// -> won't set `force = true`, preventing forced `updateMatrixWorld()` of all scene children in case the scene matrix hasn't changed.
		// -> https://github.com/mrdoob/three.js/blob/6a51509d8aeac60ac3fe0f6766a15f5342d6e643/src/core/Object3D.js#L565-L605
		scene.matrixAutoUpdate = false

		if (verbose && log_mau) console.debug(...c_mau(c_name, "disableSceneAuto! scene.autoUpdate:", scene.autoUpdate))
		if (verbose && log_mau)
			console.debug(...c_mau(c_name, "disableSceneAuto! scene.matrixAutoUpdate:", scene.matrixAutoUpdate))
	}

	$: if (scene && name) scene.name = name
	$: if (shadow_dom_el && name) shadow_dom_el.dataset.name = name

	/** ☝️ `matrix` **shorthand** attribute overrides ( *are ignored* ) `pos`, `rot`, `quat`, `scale` and `lookAt` 'shorthand' attributes! */
	export let matrix: Matrix4 | Parameters<Matrix4["set"]> = undefined

	const w_sh = PropUtils.getShortHandAttrWarnings(`SVELTHREE > ${c_name} >`)

	let sProps: SvelthreeProps

	// IMPORTANT  `props` will be overridden by 'shorthand' attributes!
	/** **shorthand** attribute for setting properties of the created / injected three.js instance via an `Object Literal`. */
	export let props: PropsScene = undefined

	$: if (!sProps && scene && props) sProps = new SvelthreeProps(scene)
	$: if (props && sProps) update_props()
	function update_props() {
		if (verbose && log_rs) console.debug(...c_rs(c_name, "props", props))
		sProps.update(props)
	}

	// IMPORTANT  following 'shorthand' attributes will override `props` attribute!

	/** **shorthand** attribute for setting the `position` property of the created / injected three.js instance. */
	export let pos: Vector3 | Parameters<Vector3["set"]> = undefined
	$: !matrix && scene && pos ? set_pos() : pos && scene ? console.warn(w_sh.pos) : null
	function set_pos() {
		if (verbose && log_rs) console.debug(...c_rs(c_name, "pos", pos))
		PropUtils.setPositionFromValue(scene, pos)
	}

	/** **shorthand** attribute for setting the `rotation` property of the created / injected three.js instance. */
	export let rot:
		| Euler
		| Parameters<Euler["set"]>
		| Quaternion
		| Parameters<Quaternion["set"]>
		| Vector3
		| Parameters<Vector3["set"]> = undefined
	$: !matrix && !quat && scene && rot ? set_rot() : rot && scene ? console.warn(w_sh.rot) : null
	function set_rot() {
		if (verbose && log_rs) console.debug(...c_rs(c_name, "rot", rot))
		PropUtils.setRotationFromValue(scene, rot)
	}

	/** **shorthand** attribute for setting the `quaternion` property of the created / injected three.js instance. */
	export let quat: Quaternion | Parameters<Quaternion["set"]> = undefined
	$: !matrix && scene && quat ? set_quat() : quat && scene ? console.warn(w_sh.quat) : null
	function set_quat() {
		if (verbose && log_rs) console.debug(...c_rs(c_name, "quat", quat))
		PropUtils.setQuaternionFromValue(scene, quat)
	}

	export let scale: Vector3 | Parameters<Vector3["set"]> | number = undefined
	$: !matrix && scene && scale ? set_scale() : scale && scene ? console.warn(w_sh.scale) : null
	function set_scale() {
		if (verbose && log_rs) console.debug(...c_rs(c_name, "scale", scale))
		PropUtils.setScaleFromValue(scene, scale)
	}

	/** */
	export let lookAt: Vector3 | Parameters<Vector3["set"]> | Targetable = undefined
	$: !matrix && scene && lookAt ? set_lookat() : lookAt && scene ? console.warn(w_sh.lookAt) : null
	function set_lookat() {
		if (verbose && log_rs) console.debug(...c_rs(c_name, "lookAt", lookAt))
		PropUtils.setLookAtFromValue(scene, lookAt)
	}

	// IMPORTANT  `matrix` 'shorthand' attribute will override all other transforms ('shorthand' attributes)!
	$: if (matrix && scene) set_matrix()
	function set_matrix(): void {
		if (verbose && log_rs) console.debug(...c_rs(c_name, "matrix", matrix))
		PropUtils.setMatrixFromValue(scene, matrix)
	}

	export let castShadow: boolean = undefined
	$: if (castShadow !== undefined && scene) scene.castShadow = castShadow

	export let receiveShadow: boolean = undefined
	$: if (receiveShadow !== undefined && scene) scene.receiveShadow = receiveShadow

	/** Scene `.background`. */
	export let bg: Texture | Color | string | number | [r: number, g: number, b: number] | Vector3 = undefined
	$: if (bg) set_bg()

	function set_bg(): void {
		if (verbose && log_rs) console.debug(...c_rs(c_name, "bg", bg))

		if (bg.constructor?.name === "Texture") {
			scene.background = bg as Texture
		} else {
			PropUtils.setColorFromValueKey(
				scene,
				bg as Color | string | number | [r: number, g: number, b: number] | Vector3,
				"background"
			)
		}
	}

	/** Scene background texture image (*url/path*) and mapping method.
	 * Loads the texture image, creates a texture and sets it as Scene `.background`.*/
	export let bg_tex: { url: string; mapping?: Mapping } = undefined
	$: if (bg_tex) set_bg_tex()

	function set_bg_tex(): Texture {
		if (verbose && log_rs) console.debug(...c_rs(c_name, "bg_tex", bg_tex))

		//  SVELTEKIT  SSR
		if (browser) {
			const env_texture_loader = new TextureLoader().load(bg_tex.url, (tex) => {
				if (bg_tex.mapping) tex.mapping = bg_tex.mapping
				scene.background = tex
			})

			return env_texture_loader
		}
	}

	/** Scene `.fog`. */
	export let fog: FogBase = undefined
	$: if (fog) set_fog()

	function set_fog(): void {
		if (verbose && log_rs) console.debug(...c_rs(c_name, "fog", bg))
		scene.fog = fog
	}

	/** Scene `.environment` texture. */
	export let env: Texture = undefined
	$: if (env) set_env()

	function set_env(): void {
		if (verbose && log_rs) console.debug(...c_rs(c_name, "env", env))
		scene.environment = env
	}

	/** Scene environment texture image (*url/path*) and mapping method (*optional, default: `EquirectangularReflectionMapping`*).
	 * Loads the texture image, creates a texture and sets it as Scene `.environment`. */
	export let env_tex: { url: string; mapping?: Mapping } = undefined
	$: if (env_tex) set_env_tex()

	function set_env_tex(): Texture {
		if (verbose && log_rs) console.debug(...c_rs(c_name, "env_tex", env_tex))

		//  SVELTEKIT  SSR
		if (browser) {
			const env_texture_loader = new TextureLoader().load(env_tex.url, (tex) => {
				tex.mapping = env_tex.mapping | EquirectangularReflectionMapping
				scene.environment = tex
			})

			return env_texture_loader
		}
	}

	/** The root scene -> `scene.parent = null`. */
	let root_scene: THREE_Scene | null = undefined
	let root_scene_obj = { value: undefined }
	let scene_obj = { value: undefined }

	$: if (root_scene === undefined) {
		root_scene = get_root_scene(getContext("scene"))

		if (root_scene === scene) {
			// we are the root scene
			root_scene = null
			root_scene_obj.value = root_scene
			scene_obj.value = scene
		} else {
			root_scene_obj.value = root_scene
			scene.userData.root_scene = root_scene
			scene_obj.value = scene
		}
	}

	type BoxHelperParams = ConstructorParameters<typeof BoxHelper>
	export let boxParams: RemoveFirst<BoxHelperParams> = undefined
	/** Creates and adds a `BoxHelper`. */
	export let box: boolean = undefined

	/** Removes `WebGLRenderer` `"update_helpers"` event listener. */
	let remove_update_box_on_render_event: () => void = undefined

	$: if (box && scene && root_scene && !scene.userData.box) add_box_helper()
	$: if (!box && scene?.userData.box) remove_box_helper()

	function add_box_helper() {
		if (boxParams) {
			scene.userData.box = new BoxHelper(scene, ...boxParams)
		} else {
			scene.userData.box = new BoxHelper(scene)
		}

		scene.userData.box.visible = false
	}

	// update and show box on next frame
	$: if (box && scene && scene.userData.box && $svelthreeStores[sti].rendererComponent && root_scene) {
		apply_box()
	}

	function apply_box(): void {
		if (!scene.userData.box.parent) {
			// add all boxes to the root scene!
			root_scene.add(scene.userData.box)
		}

		// update box and make it visible
		scene.userData.box.update()
		scene.userData.box.visible = true

		// start updating
		if (!remove_update_box_on_render_event) {
			remove_update_box_on_render_event = $svelthreeStores[sti].rendererComponent.$on(
				"update_helpers",
				update_box
			)
		}
	}

	function update_box(): void {
		// `scene` may have been nullified by `clear()`
		if (scene) scene.userData.box.update()
	}

	function remove_box_helper(): void {
		if (remove_update_box_on_render_event) {
			remove_update_box_on_render_event()
			remove_update_box_on_render_event = null
		}

		// `scene` may have been nullified by `clear()`
		if (scene?.userData.box?.parent) {
			scene.userData.box.parent.remove(scene.userData.box)
			scene.userData.box = null
		}
	}

	/** Make component's three.js object interactive -> enable raycasting, `on:<event_name>` directives and `on_<event_name>` internal actions. */
	export let interact: boolean = undefined

	/**
	Adds component's three.js object instance to the `raycast` array even if it's not set to `interact` ( _no interaction listeners_ ).
	* This way the object acts as a pure _interaction occluder / blocker_ -> will be detected / intersected by `Raycaster`'s ray.
	* 
	* Setting the `block` prop makes sense only if the `interact` prop is not set / set to `false`.  
	* In case `interact` prop is set / set to `true`, but no e.g. `on:<event_name>` directives or `on_<event_name>` internal actions are set,
	* the object will automatically become an _interaction occluder / blocker_.
   */
	export let block = false

	const interaction_on_clear = {
		interact: undefined,
		block: undefined
	}

	$: if (scene) restore_interaction_props()
	async function restore_interaction_props(): Promise<void> {
		//console.warn(`comp '${name}' restore_interaction_props!`, { scene, scene_uuid, interact: scene.userData.interact })
		if (typeof interaction_on_clear.interact === "boolean") {
			await tick()

			//console.warn(`comp '${name}' restoring 'interact' prop!`, interaction_on_clear.interact)
			interact = interaction_on_clear.interact
			interaction_on_clear.interact = null

			if (interaction_on_clear.block !== undefined && interaction_on_clear.block !== null) {
				//console.warn(`comp '${name}' restoring 'block' prop!`, interaction_on_clear.block)
				block = interaction_on_clear.block
				interaction_on_clear.block = null
			}
		}
	}

	let interactive: boolean = undefined
	const canvas_interactivity: Writable<{ enabled: boolean }> = getContext("canvas_interactivity")

	$: interactive = $canvas_interactivity.enabled

	let interactionEnabled: boolean = undefined
	$: interactionEnabled = interactive && interact

	//  IMPORTANT  not reactive
	const raycast: RaycastArray = getContext("raycast")

	// Reactively ENABLE raycasting to the created three.js instance. Only `interact` is set and `block` is false (default).
	// + `block` will be changed automatically based on pointer listeners total count via `SvelthreeInteraction` component.
	$: if (interactionEnabled && raycast && !block) {
		if (!raycast.includes(scene)) {
			scene.userData.block = false
			raycast.push(scene)
		} else {
			scene.userData.block = false
		}
	}

	// Reactively ENABLE raycasting to the created three.js instance -> 'interaction occluder / blocker'.
	// Only `block` is set / `true` but no `interact` / set to `false`. Since `interact` is `false`,
	// `block` will NOT be changed via `SvelthreeInteraction` component (not rendered).
	$: if (!interactionEnabled && raycast && block) {
		if (!raycast.includes(scene)) {
			scene.userData.block = true
			raycast.push(scene)
		} else {
			scene.userData.block = true
		}
	}

	// Reactively DISABLE raycasting to the created three.js instance. Neither `block` nor `interact` are set / are both `false`.
	// Since `interact` is `false`, `block` will NOT be changed via `SvelthreeInteraction` component (not rendered).
	$: if (!interactionEnabled && raycast && !block) {
		if (raycast.includes(scene)) {
			raycast.splice(scene.userData.index_in_raycast, 1)
			scene.userData.block = false
		}
	}

	/** `SvelthreeInteraction` component reference used for reactive listener management only. */
	let interaction_comp = undefined

	/**
	 * **svelthree** replacement for [`$on`](https://svelte.dev/docs#run-time-client-side-component-api-$on), does basically the same,
	 * but it doesn't return a function for removal of the listener (_like Svelte native does_), instead use `.onx(type, callback)` syntax.
	 * Needed for **reactive** interaction listener management -> _internal svelthree functionality_.
	 *
	 * ☝️ _Can be used with **interactive components only** -> `interact` prop has to be `true`._
	 */
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	export const on = async (type: any, callback: any): Promise<void> => {
		if (interact) {
			if (!interaction_comp || !shadow_dom_el) await tick()

			self.$on(type, callback)
			interaction_comp.update_listeners = true
		} else {
			console.error(
				"SVELTHREE > Mesh > on : You can call the '.on(...)' function with interactive components only! Component's 'interact' prop has to be 'true'."
			)
		}
	}

	/**
	 * **svelthree** replacement for the _event listener removal function_ returned by [`$on`](https://svelte.dev/docs#run-time-client-side-component-api-$on), does basically the same,
	 * needed for **reactive** interaction listener management -> _internal svelthree functionality_. It additionaly allows programmatic removal of all callbacks of a certain type and
	 * programmatic removal of 'forwarding' directives (no handlers) like `on:click`.
	 *
	 * ☝️ _Can be used with **interactive components only** -> `interact` prop has to be `true`._
	 */
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	export const onx = async (type: any, callback: any): Promise<void> => {
		if (interact) {
			if (!interaction_comp || !shadow_dom_el) await tick()

			const cbacks = self.$$.callbacks[type]
			if (callback) {
				const index = cbacks.indexOf(callback)
				if (index !== -1) cbacks.splice(index, 1)
			} else {
				// allows e.g. onx("click") -> will remove all callbacks and the callback type itself
				// this way we can also programatically delete 'forwarding' directives (no handlers) like `on:click`
				self.$$.callbacks[type].length = 0
				delete self.$$.callbacks[type]
			}

			interaction_comp.update_listeners = true
		} else {
			console.error(
				"SVELTHREE > Mesh > onx : You can call the '.onx(...)' function with interactive components only! Component's 'interact' prop has to be 'true'!"
			)
		}
	}

	/** Interaction modifiers. */
	export let modifiers: SvelthreeModifiersProp = undefined

	export let on_click: SvelthreePointerEventHandler = undefined
	$: if (on_click !== undefined && interaction_comp && shadow_dom_el) {
		interaction_comp.update_listeners = true
	}

	export let on_pointerup: SvelthreePointerEventHandler = undefined
	$: if (on_pointerup !== undefined && interaction_comp && shadow_dom_el) {
		interaction_comp.update_listeners = true
	}

	export let on_pointerdown: SvelthreePointerEventHandler = undefined
	$: if (on_pointerdown !== undefined && interaction_comp && shadow_dom_el) {
		interaction_comp.update_listeners = true
	}

	export let on_pointerover: SvelthreePointerEventHandler = undefined
	$: if (on_pointerover !== undefined && interaction_comp && shadow_dom_el) {
		interaction_comp.update_listeners = true
	}

	export let on_pointerout: SvelthreePointerEventHandler = undefined
	$: if (on_pointerout !== undefined && interaction_comp && shadow_dom_el) {
		interaction_comp.update_listeners = true
	}

	export let on_pointermove: SvelthreePointerEventHandler = undefined
	$: if (on_pointermove !== undefined && interaction_comp && shadow_dom_el) {
		interaction_comp.update_listeners = true
	}

	export let on_pointermoveover: SvelthreePointerEventHandler = undefined
	$: if (on_pointermoveover !== undefined && interaction_comp && shadow_dom_el) {
		interaction_comp.update_listeners = true
	}

	export let on_keydown: SvelthreeKeyboardEventHandler = undefined
	$: if (on_keydown !== undefined && interaction_comp && shadow_dom_el) {
		interaction_comp.update_listeners = true
	}

	export let on_keypress: SvelthreeKeyboardEventHandler = undefined
	$: if (on_keypress !== undefined && interaction_comp && shadow_dom_el) {
		interaction_comp.update_listeners = true
	}

	export let on_keyup: SvelthreeKeyboardEventHandler = undefined
	$: if (on_keyup !== undefined && interaction_comp && shadow_dom_el) {
		interaction_comp.update_listeners = true
	}

	export let on_focus: SvelthreeFocusEventHandler = undefined
	$: if (on_focus !== undefined && interaction_comp && shadow_dom_el) {
		interaction_comp.update_listeners = true
	}

	export let on_blur: SvelthreeFocusEventHandler = undefined
	$: if (on_blur !== undefined && interaction_comp && shadow_dom_el) {
		interaction_comp.update_listeners = true
	}

	export let on_focusin: SvelthreeFocusEventHandler = undefined
	$: if (on_focusin !== undefined && interaction_comp && shadow_dom_el) {
		interaction_comp.update_listeners = true
	}

	export let on_focusout: SvelthreeFocusEventHandler = undefined
	$: if (on_focusout !== undefined && interaction_comp && shadow_dom_el) {
		interaction_comp.update_listeners = true
	}

	export let on_wheel: SvelthreeWheelEventHandler = undefined // ->  TODO  implement
	$: if (on_wheel !== undefined && interaction_comp && shadow_dom_el) {
		interaction_comp.update_listeners = true
	}

	export let on_wheelover: SvelthreeWheelEventHandler = undefined // -> TODO  implement
	$: if (on_wheelover !== undefined && interaction_comp && shadow_dom_el) {
		interaction_comp.update_listeners = true
	}

	/** Animation logic to be performed with the (three) object instance created by the component. */
	export let animation: SvelthreeAnimationFunction = undefined

	let animationEnabled = false
	$: if (animation) animationEnabled = true

	/** Immediately start provided animation, default: `false`. Alternative: `<component_reference>.start_animation()` or shorter `.start_ani()`. */
	export let aniauto: boolean = undefined

	/** (_internal_) reference to the `SvelthreeAni` instance */
	let ani: SvelthreeAni
	$: if (animation && animationEnabled) ani = new SvelthreeAni(scene, scene, animation, aniauto)

	let currentSceneActive = undefined
	$: currentSceneActive = $svelthreeStores[sti].scenes[scene.userData.index_in_scenes]?.isActive
	$: if (ani && currentSceneActive !== undefined) ani.onCurrentSceneActiveChange(currentSceneActive)

	/** Removes the (three) instance created by / provided to the component from it's parent. */
	export const remove_instance_from_parent = async (): Promise<boolean> => {
		const removed: boolean = remove_instance(scene, "scene")
		return removed
	}
	/**
	 * Same as `remove_instance_from_parent()` just shorter syntax.
	 * Removes the (three) instance of the object created by the component from it's parent.
	 */
	export const remove = remove_instance_from_parent

	/** Returns the (three) instance of the object created by the component. */
	export const get_instance = (): THREE_Scene => scene

	/** Returns the `animation` object. */
	export const get_animation = (): SvelthreeAnimation => ani.getAnimation()
	/** Same as `get_animation()` just shorter syntax. Returns the `animation` object. */
	export const get_ani = get_animation

	/** Starts the `animation` object. */
	export const start_animation = (): void => ani.startAnimation()
	/** Same as `start_animation()` just shorter syntax. Starts the `animation` object. */
	export const start_ani = start_animation

	/** Sets `focus()` on the component / it's shadow dom element. */
	export const focused = (): void => shadow_dom_el.focus()

	/**
	 * Primarily for internal usage. Clears all references to the currently managed three.js instance.
	 * Called by `remove_instance(...)` / `clear_old_component()` if the instance has been
	 * assigned to some other component (_before_).
	 */
	export const clear = () => {
		//console.warn(`CLEAR! -> ${name}`)

		interaction_on_clear.interact = interact
		interaction_on_clear.block = block
		interact = null

		scene = null

		// IMPORTANT //
		// has to be set to `null`, `undefined` would set `scene_uuid` if a cleared component recevies a scene
		// we don't want that, beacuse then the `handle_instance_change` wouldn't be triggered!
		scene_uuid = null
	}

	import type { SvelthreeComponentShadowDOMChild } from "../types/types-extra"
	const generated_children: SvelthreeComponentShadowDOMChild[] = []
	const user_created_children: SvelthreeComponentShadowDOMChild[] = []

	/**
	 * Pushes a user-created (_e.g. via `new Mesh({...})`_) or an internally generated / created (e.g. via `SvelthreeGLTF.apply(...)`) `svelthree`-component
	 * to a corresponding Array containing all user-created / internally generated (_registered_) child components, in order for them to be destroyed at the same time
	 * the parent component gets destroyed (_`onDestroy`_). See also `comp_ref.get_user_created_children()` and `comp_ref.get_generated_children()`.
	 */
	export const register_child_component = (
		component: SvelthreeComponentShadowDOMChild,
		generated?: boolean
	): SvelthreeComponentShadowDOMChild[] => {
		if (generated) {
			if (!generated_children.includes(component)) {
				generated_children.push(component)
			}

			return generated_children
		} else {
			if (!user_created_children.includes(component)) {
				user_created_children.push(component)
			}

			return user_created_children
		}
	}

	function destroy_registered_child_components(arr: SvelthreeComponentShadowDOMChild[]) {
		if (arr.length) {
			for (let i = 0; i < arr.length; i++) {
				const child_comp: SvelthreeComponentShadowDOMChild = arr[i]
				if (child_comp) child_comp.$destroy()
				arr[i] = null
			}

			arr.length = 0
		}
	}

	export const get_user_created_children = (): SvelthreeComponentShadowDOMChild[] => user_created_children
	export const get_generated_children = (): SvelthreeComponentShadowDOMChild[] => generated_children

	/** **Completely replace** `onMount` -> any `onMount_inject_before` & `onMount_inject_after` will be ignored.
	 * _default verbosity will be gone!_ */
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	export let onMount_replace: (args?: any) => any = undefined

	onMount(
		onMount_replace
			? async () => onMount_replace(_self)
			: async () => {
					if (verbose && log_lc && (log_lc.all || log_lc.om)) {
						console.info(...c_lc(c_name, "onMount"))
					}

					if (verbose && log_mau) {
						console.debug(
							...c_mau(c_name, "onMount : scene.", {
								matrixAutoUpdate: scene.matrixAutoUpdate,
								matrixWorldNeedsUpdate: scene.matrixWorldNeedsUpdate
							})
						)
					}
			  }
	)

	/** **Inject** functionality **before** component's existing `onDestroy` logic.
	 * _default verbosity not affected._ */
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	export let onDestroy_inject_before: (args?: any) => any = undefined

	/** **Inject** functionality **after** component's existing `onDestroy` logic.
	 * _default verbosity not affected._ */
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	export let onDestroy_inject_after: (args?: any) => any = undefined

	/** **Completely replace** `onDestroy` -> any `onDestroy_inject_before` & `onDestroy_inject_after` will be ignored.
	 * _default verbosity will be gone!_ */
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	export let onDestroy_replace: (args?: any) => any = undefined

	onDestroy(
		onDestroy_replace
			? async () => onDestroy_replace(_self)
			: async () => {
					if (verbose && log_lc && (log_lc.all || log_lc.od)) {
						console.info(...c_lc(c_name, "onDestroy"))
					}

					if (verbose && log_mau) {
						console.debug(
							...c_mau(c_name, "onDestroy : scene.", {
								matrixAutoUpdate: scene.matrixAutoUpdate,
								matrixWorldNeedsUpdate: scene.matrixWorldNeedsUpdate
							})
						)
					}

					if (onDestroy_inject_before) onDestroy_inject_before()

					remove_box_helper()
					if (ani) ani.destroyAnimation()

					destroy_registered_child_components(generated_children)
					destroy_registered_child_components(user_created_children)

					if (onDestroy_inject_after) onDestroy_inject_after()
			  }
	)

	/** **Completely replace** `beforeUpdate` -> any `beforeUpdate_inject_before` & `beforeUpdate_inject_after` will be ignored.
	 * _default verbosity will be gone!_ */
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	export let beforeUpdate_replace: (args?: any) => any = undefined

	beforeUpdate(
		beforeUpdate_replace
			? async () => beforeUpdate_replace(_self)
			: async () => {
					if (verbose && log_lc && (log_lc.all || log_lc.bu)) {
						console.info(...c_lc(c_name, "beforeUpdate"))
					}

					if (verbose && log_mau) {
						console.debug(
							...c_mau(c_name, "beforeUpdate : scene.", {
								matrixAutoUpdate: scene.matrixAutoUpdate,
								matrixWorldNeedsUpdate: scene.matrixWorldNeedsUpdate
							})
						)
					}
			  }
	)

	/** **Inject** functionality **before** component's existing `afterUpdate` logic.
	 * _default verbosity not affected._ */
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	export let afterUpdate_inject_before: (args?: any) => any = undefined

	/** **Inject** functionality **after** component's existing `afterUpdate` logic.
	 * _default verbosity not affected._ */
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	export let afterUpdate_inject_after: (args?: any) => any = undefined

	/** **Completely replace** `afterUpdate` -> any `afterUpdate_inject_before` & `afterUpdate_inject_after` will be ignored.
	 * _default verbosity will be gone!_ */
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	export let afterUpdate_replace: (args?: any) => any = undefined

	afterUpdate(
		afterUpdate_replace
			? async () => afterUpdate_replace(_self)
			: async () => {
					if (verbose && log_lc && (log_lc.all || log_lc.au)) {
						console.info(...c_lc(c_name, "afterUpdate"))
					}

					if (verbose && log_mau) {
						console.debug(
							...c_mau(c_name, "afterUpdate : scene.", {
								matrixAutoUpdate: scene.matrixAutoUpdate,
								matrixWorldNeedsUpdate: scene.matrixWorldNeedsUpdate
							})
						)
					}

					if (afterUpdate_inject_before) afterUpdate_inject_before()

					// Update local matrix after all (props) changes (async microtasks) have been applied.
					if (scene && !scene.matrixAutoUpdate) scene.updateMatrix()

					if (verbose && !scene.matrixAutoUpdate && log_mau) {
						console.debug(
							...c_mau(c_name, "afterUpdate : scene.", {
								matrixAutoUpdate: scene.matrixAutoUpdate,
								matrixWorldNeedsUpdate: scene.matrixWorldNeedsUpdate
							})
						)
					}

					if ($svelthreeStores[sti].rendererComponent?.mode === "auto") {
						if (root_scene) {
							// we're not the root scene (root_scene is not `null`)
							// prevent an additional component update by not accessing the `root_scene` prop directly.
							root_scene_obj.value.userData.dirty = true
							$svelthreeStores[sti].rendererComponent.schedule_render_auto(root_scene)
						} else {
							// we're are the root scene (root_scene is `null`)
							// prevent an additional component update by not accessing the `scene` prop directly.
							scene_obj.value.userData.dirty = true
							$svelthreeStores[sti].rendererComponent.schedule_render_auto(scene)
						}
					}

					if (afterUpdate_inject_after) afterUpdate_inject_after()
			  }
	)
</script>

<slot />

{#if $svelthreeStores[sti].renderer && $svelthreeStores[sti].renderer.xr.enabled === false && interact}
	<SvelthreeInteraction
		bind:this={interaction_comp}
		{shadow_dom_el}
		{modifiers}
		{dispatch_interaction}
		obj={scene}
		parent={self}
		{interactionEnabled}
		{log_dev}
		{log_lc}
	/>
{/if}
